core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include( 'home.urls' , namespace='home')),
    path('accounts/', include( 'accounts.urls' , namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path , include
from . import views

app_name = 'home'

bucket_urls = [
	path('', views.BucketView.as_view(), name='bucket'),
	path('obj_del/<key>' , views.Delete_obj_BucketView.as_view() , name='bucket_del_obj'),
	path('download_obj/<str:key>/', views.DownloadBucketObject.as_view(), name='download_obj_bucket'),
]

urlpatterns = [
    path('' , views.HomeView.as_view() , name='home'),
    path('bucket/', include(bucket_urls)),
    path('bucket_obj_del/<key>' , views.Delete_obj_BucketView.as_view() , name='bucket_del_obj'),
    path('<slug:slug>/' , views.ProductDetailView.as_view() , name='detail_view'),
]

home/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length = 200)
    slug = models.SlugField(max_length = 200 , unique= True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'My_category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    Category = models.ForeignKey(Category , on_delete = models.CASCADE , related_name = 'products')
    name = models.CharField(max_length = 200)
    slug = models.SlugField(max_length = 200 , unique= True)
    image = models.ImageField() #upload_to='products/%Y/%m/%d/'
    description = models.TextField()
    price = models.IntegerField()
    available = models.BooleanField(default = True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ('name', )


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home:detail_view', args=[self.slug,])

# Create your models here.

home/views.py
from django.shortcuts import render , redirect
from django.views import View
from .models import Product
from django.shortcuts import get_object_or_404 
from . import tasks
from django.contrib import messages
from utils import IsAdminUserMixin



# Create your views here.

class HomeView(View):

    def get(self, request):
        products = Product.objects.filter(available = True)
        return render(request , 'home/home.html' , {'products':products})
    

class ProductDetailView(View):
    def get(self , request , slug ):
        product = get_object_or_404(Product , slug=slug)
        return render(request , 'home/detail.html' , {'product':product})
    

class BucketView(IsAdminUserMixin , View):
        template_name = 'home/bucket.html'
        def get(self, request):
            objects = tasks.all_bucket_objects_task()
            print(objects)
            return render(request , self.template_name , {'objects' : objects} )


class Delete_obj_BucketView(IsAdminUserMixin , View):
     
     def get(self,request ,key):
          tasks.delete_object_task.delay(key)
          messages.success(request , 'your object delete after a wihle')
          return redirect('home:bucket')


class DownloadBucketObject(IsAdminUserMixin , View):
	def get(self, request, key):
		tasks.download_object_task.delay(key)
		messages.success(request, 'your download will start soon.', 'info')
		return redirect('home:bucket')

          

home/templates/home/bucket.html
{% extends 'base.html' %}



{% block content %}

<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Size</th>
        <th scope="col">Download</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for obj in objects %}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          <td>{{obj.Key}}</td>
          <td>{{obj.Size | filesizeformat }}</td>
          <td><a href="{% url 'home:download_obj_bucket' obj.Key %}">download</a></td>
          <td><a href=" {% url 'home:bucket_del_obj' obj.Key %}"> Delete </a></td>
        </tr>
      {% endfor %}
    
    </tbody>
  </table>
    
{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}



{% block content %}

 
<h3>{{product.name}}</h3>
<small>{{product.created}}</small><br>
<img src="{{ product.image.url}}">
    
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block extra_headers %}
<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
 {% endblock %}

{% block content %}
    <h3> foroozan khanooooom khoda hast , khoda dooset dare ...  </h3>
    <h3> khodaya dooset daram </h3>

    {% for product in products %}
        <div class="card" style="width: 18rem;">
            <img src="{{ product.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">
            <a href="{{ product.get_absolute_url }}" class="card-title"> {{ product.name }} </a>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
      </div>
    {% endfor %}
{% endblock %}